# Generated by Django 3.1.3 on 2021-05-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210513_1353'),
        ('articles', '0002_remove_article_adminupload'),
    ]

    operations = [
    ]
