# Generated by Django 3.1.3 on 2021-05-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210515_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='comment',
            name='date_comment',
            field=models.DateTimeField(auto_now_add=True, default='2021-12-12 10:24', verbose_name='Дата создания комментария'),
            preserve_default=False,
        ),
    ]
