# Generated by Django 3.1.3 on 2021-06-07 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_for_chart', models.IntegerField(default='1', verbose_name='Значение для диаграммы')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('host_name', models.CharField(default='', max_length=50, verbose_name='Хост компьютера')),
                ('dept', models.CharField(default='', max_length=50, verbose_name='Отдел работы')),
                ('task', models.TextField(verbose_name='Описание')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Коментарий от исполнителя')),
                ('comment_author', models.TextField(blank=True, default='', null=True, verbose_name='Отзыв заявителя')),
                ('status_task', models.CharField(choices=[('Заявка отправлена', 'Заявка отправлена'), ('Заявка прочитана', 'Заявка прочитана'), ('Исполнитель назначен', 'Исполнитель назначен'), ('Заявка выполнена', 'Заявка выполнена'), ('Заявка отклонена', 'Заявка отклонена')], default='Заявка отправлена', help_text='Указывайте только актуальные статусы', max_length=50, verbose_name='Статус заказа')),
                ('in_progress_time', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_user_type', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(blank=True, default=None, help_text='Укажите исполнителя и поменяйте статус на "Исполнитель назначен"', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_contractor_type', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задачу',
                'verbose_name_plural': 'Задачи',
                'permissions': (('can_mark_returned', 'Set book as returned'),),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Хост компьютера')),
                ('dept', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Отдел работы')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='user-profile-photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
