# Generated by Django 3.1.3 on 2021-05-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('img_main', models.ImageField(upload_to='userManual/', verbose_name='Главное изображение')),
                ('description_main', models.TextField(verbose_name='Основное описание')),
                ('url', models.SlugField(max_length=160)),
                ('date_publiched', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации руководства')),
                ('relevancy', models.BooleanField(default=False, verbose_name='Актуальность')),
                ('img_two', models.ImageField(upload_to='userManual/', verbose_name='Изображение №2')),
                ('description_two', models.TextField(verbose_name='Описание №2')),
                ('img_three', models.ImageField(upload_to='userManual/', verbose_name='Изображение №3')),
                ('description_three', models.TextField(verbose_name='Описание №3')),
                ('img_four', models.ImageField(upload_to='userManual/', verbose_name='Изображение №4')),
                ('description_four', models.TextField(verbose_name='Описание №4')),
                ('img_five', models.ImageField(upload_to='userManual/', verbose_name='Изображение №5')),
                ('description_five', models.TextField(verbose_name='Описание №5')),
                ('img_six', models.ImageField(upload_to='userManual/', verbose_name='Изображение №6')),
                ('description_six', models.TextField(verbose_name='Описание №6')),
                ('img_seven', models.ImageField(upload_to='userManual/', verbose_name='Изображение №7')),
                ('description_seven', models.TextField(verbose_name='Описание №7')),
                ('img_eight', models.ImageField(upload_to='userManual/', verbose_name='Изображение №8')),
                ('description_eight', models.TextField(verbose_name='Описание №8')),
                ('img_nine', models.ImageField(upload_to='userManual/', verbose_name='Изображение №9')),
                ('description_nine', models.TextField(verbose_name='Описание №9')),
            ],
            options={
                'verbose_name': 'Руководство пользователя',
                'verbose_name_plural': 'Руководства пользователя',
                'managed': True,
            },
        ),
    ]
