# Generated by Django 3.1.3 on 2021-06-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanual',
            name='img_main',
            field=models.ImageField(upload_to='userManual/', verbose_name='Главное изображение'),
        ),
    ]
