# Generated by Django 3.1.3 on 2021-05-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanual',
            name='description_eight',
            field=models.TextField(null=True, verbose_name='Описание №8'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_five',
            field=models.TextField(null=True, verbose_name='Описание №5'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_four',
            field=models.TextField(null=True, verbose_name='Описание №4'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_main',
            field=models.TextField(null=True, verbose_name='Основное описание'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_nine',
            field=models.TextField(null=True, verbose_name='Описание №9'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_seven',
            field=models.TextField(null=True, verbose_name='Описание №7'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_six',
            field=models.TextField(null=True, verbose_name='Описание №6'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_three',
            field=models.TextField(null=True, verbose_name='Описание №3'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_two',
            field=models.TextField(null=True, verbose_name='Описание №2'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_eight',
            field=models.ImageField(null=True, upload_to='userManual/', verbose_name='Изображение №8'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_five',
            field=models.ImageField(null=True, upload_to='userManual/', verbose_name='Изображение №5'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_four',
            field=models.ImageField(null=True, upload_to='userManual/', verbose_name='Изображение №4'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_main',
            field=models.ImageField(null=True, upload_to='userManual/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_nine',
            field=models.ImageField(null=True, upload_to='userManual/', verbose_name='Изображение №9'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_seven',
            field=models.ImageField(null=True, upload_to='userManual/', verbose_name='Изображение №7'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_six',
            field=models.ImageField(null=True, upload_to='userManual/', verbose_name='Изображение №6'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_three',
            field=models.ImageField(null=True, upload_to='userManual/', verbose_name='Изображение №3'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_two',
            field=models.ImageField(null=True, upload_to='userManual/', verbose_name='Изображение №2'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='url',
            field=models.SlugField(max_length=160, null=True),
        ),
    ]
