# Generated by Django 3.1.3 on 2021-06-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManual', '0002_auto_20210609_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanual',
            name='img_main',
            field=models.ImageField(blank=True, null=True, upload_to='userManual/', verbose_name='Главное изображение'),
        ),
    ]
