# Generated by Django 3.1.3 on 2021-05-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManual', '0002_auto_20210509_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanual',
            name='description_eight',
            field=models.TextField(blank=True, null=True, verbose_name='Описание №8'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_five',
            field=models.TextField(blank=True, null=True, verbose_name='Описание №5'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_four',
            field=models.TextField(blank=True, null=True, verbose_name='Описание №4'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_main',
            field=models.TextField(default='', verbose_name='Основное описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_nine',
            field=models.TextField(blank=True, null=True, verbose_name='Описание №9'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_seven',
            field=models.TextField(blank=True, null=True, verbose_name='Описание №7'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_six',
            field=models.TextField(blank=True, null=True, verbose_name='Описание №6'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_three',
            field=models.TextField(blank=True, null=True, verbose_name='Описание №3'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='description_two',
            field=models.TextField(blank=True, null=True, verbose_name='Описание №2'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_eight',
            field=models.ImageField(blank=True, default='', upload_to='userManual/', verbose_name='Изображение №8'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_five',
            field=models.ImageField(blank=True, default='', upload_to='userManual/', verbose_name='Изображение №5'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_four',
            field=models.ImageField(blank=True, default='', upload_to='userManual/', verbose_name='Изображение №4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_main',
            field=models.ImageField(blank=True, default='', upload_to='userManual/', verbose_name='Главное изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_nine',
            field=models.ImageField(blank=True, default='', upload_to='userManual/', verbose_name='Изображение №9'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_seven',
            field=models.ImageField(blank=True, default='', upload_to='userManual/', verbose_name='Изображение №7'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_six',
            field=models.ImageField(blank=True, default='', upload_to='userManual/', verbose_name='Изображение №6'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_three',
            field=models.ImageField(blank=True, default='', upload_to='userManual/', verbose_name='Изображение №3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='img_two',
            field=models.ImageField(blank=True, default='', upload_to='userManual/', verbose_name='Изображение №2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='relevancy',
            field=models.BooleanField(default=False, null=True, verbose_name='Актуальность'),
        ),
        migrations.AlterField(
            model_name='usermanual',
            name='url',
            field=models.SlugField(blank=True, default='', max_length=160),
            preserve_default=False,
        ),
    ]
