# Generated by Django 3.1.3 on 2021-06-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManual', '0003_auto_20210609_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanual',
            name='relevancy',
        ),
        migrations.RemoveField(
            model_name='usermanual',
            name='url',
        ),
    ]
