# Generated by Django 3.1.3 on 2021-06-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManual', '0004_auto_20210609_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanual',
            name='description_main',
            field=models.TextField(default=False, verbose_name='main_desc'),
        ),
    ]
